config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :tests

  map.resources :categories, :requirements => {:id => /\d+/}, :only => [:index, :show] do |categories|
    categories.resources :books, :only => [:index, :show]
  end
  map.namespace :admin do |a|
    a.resources :categories, :requirements => {:id => /\d+/}, :only => [:edit, :update, :new, :create, :destroy]
    a.resources :books, :requirements => {:id => /\d+/}, :only => [:edit, :update, :new, :create, :destroy]
  end

  

  map.root :controller => "categories"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/category.rb
class Category < ActiveRecord::Base
  # Associations
  has_many :languages, :dependent => :destroy
  has_many :subcategories
  belongs_to :redirect, :class_name => 'Category', :foreign_key => 'redirect_id'
  has_many :books

  accepts_nested_attributes_for :languages
  accepts_nested_attributes_for :books

  def has_bibliography?
    return false if books.empty?
    books.each {|book| return true unless book.modern}
    return false
  end

  def has_modern?
    return false if books.empty?
    books.each {|book| return true if book.modern}
    return false
  end

  def redirect_title
    redirect.title if redirect
  end

  def redirect_title=(name)
    self.redirect = Category.find_or_create_by_title(name) unless name.blank?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout 'admin'
  before_filter :init_layout
  before_filter :verify_login, :only => [:index, :edit, :new, :list]

  def init_layout
    @title = 'Categories'
    @cat_expanded = true
  end

  def index
    @categories = Category.find(:all, :order => 'modified_at DESC, created_at DESC', :limit => '10')
    @category = Category.new
    @category.languages = [Language.new]
    @subtitle = 'Dashboard'
  end

  def list
    @categories = Category.find(:all, :order => 'title ASC')
    @subtitle = 'View All'
    render :partial => 'list', :layout => 'admin'
  end

  def edit
    @category = Category.find params[:id]
    @category.languages << Language.new
    @subtitle = 'Edit ' + @category.title
  end

  def update
    # Either id or create new both not both
    if !params[:category][:redirect_id].blank?
      params[:category].delete(:redirect_title) 
    elsif !params[:category][:redirect_title].blank?
      params[:category].delete(:redirect_id)
    else
      params[:category].delete(:redirect_title) 
      params[:category][:redirect_id] = nil
    end
    
    @cat = Category.find params[:id]
    @cat.modified_at = Time.now

    # Fix language bug
    if params[:category][:languages_attributes]['0'][:language].blank? || params[:category][:languages_attributes]['0'][:words].blank?
      params[:category].delete :languages_attributes
      params[:category][:language_ids] = [] 
    end

    # Remove nested attribute because I did it myself
    params[:category].delete :books_attributes if params[:category].has_key? :books_attributes

    if @cat.update_attributes params[:category]
      flash[:notice] = 'Category succesfully updated!'
      redirect_to :action => 'add_books', :id => params[:id]
    else
      flash[:error] =  'Problem updating Category.'
      render 'edit'
    end
  end

  def attach
    @cat = Category.find params[:id]
    @cat.modified_at = Time.now

    if @cat.update_attributes params[:category]
      flash[:notice] = 'Books succcesfully added'
      redirect_to :action => 'index'
    else
      flash[:error] =  'Problem adding books.'
      render 'add_books'
    end
  end

  def create
    if params[:category][:languages_attributes][0][:language].blank? || params[:category][:languages_attributes][0][:words].blank?
      params[:category].delete :languages_attributes
      params[:category][:language_ids] = [] 
    end
    @category = Category.new params[:category]

    if @category.save
      flash[:notice] = 'Category succesfully created!'
      redirect_to :action => 'add_books', :id => params[:id]
    else
      render 'new'
    end
  end

  def add_books
    @category = Category.find params[:id], :include => :books
    @subtitle = 'Attach Books'
  end

  def destroy
    @category = Category.find(params[:id])

    if @category.destroy
      flash[:notice] =  'Category successfully deleted.'
    else
      flash[:error] =  'Category couldn\'t be deleted.'
    end

    redirect_to :action => 'list'
  end

  def new
    @category = Category.new
    @category.languages = [Language.new]
    @subtitle = 'Add A Category'
  end

  def debug
    @subtitle = 'Testing'
    @text = session.inspect
  end

  def search
    respond_to do |format|
      format.js do 
        cats = Category.find(:all, :conditions => ['title LIKE ?', '%' + params[:term] + '%'], :limit => 5, :order => 'title ASC')
        options = cats.collect {|cat| {:label => cat.title, :value => '', :id => cat.id}}
        options = [{:label => 'No Matches', :value => '', :id => ''}] if cats.empty?
        render :text => options.to_json
      end
    end
  end

  def sub_search
    respond_to do |format|
      format.js do 
        cats = Subcategory.find(:all, :conditions => ['title LIKE ?', '%' + params[:term] + '%'], :limit => 5, :order => 'title ASC')
        options = cats.collect {|cat| {:label => cat.title, :value => '', :id => cat.id}}
        options = [{:label => 'No Matches', :value => '', :id => ''}] if cats.empty?
        render :text => options.to_json
      end
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :menu
  
  def index
  end

  def show
    @category = Category.find params[:id], :include => :redirect
    if !@category.redirect.blank?
      redirect_to :action => 'show', :id => @category.redirect.id
    end
    @width = '33%' #@category.modern ? '33%' : '50%'
  end

  def menu
    cats = Category.find(:all, :order => 'title ASC')
    @menu_categories = {}
    @alphabet = ('a'..'z').to_a
    cats.each do |category|
      @menu_categories[category.title[0...1].downcase] = [] if @menu_categories[category.title[0...1].downcase].nil?
      @menu_categories[category.title[0...1].downcase] << category
    end
  end  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<% form_for [:admin, @category] do |f| %>
  <h3>Essentials</h3>
  <fieldset>
    <p><label>Title:</label><%= f.text_field :title, :class => 'text-long' %></p>
    <p><label>Redirect To:</label>
      <%= f.text_field :redirect_title, :class => 'text-long ac_redirect' %>
      <input type="hidden" name="category[redirect_id]" >
    </p>
    <div class="ui-state-highlight redirect">
      <span class="ui-icon ui-icon-radio-on bullet"></span>
      <span id="redirect"></span>
      <a href="javascript:void(0)" class="close"><span class="ui-icon ui-icon-close"></span></a>
    </div>
  </fieldset>

    <h3>Category Text</h3>
    <fieldset>
      <p><label>Authorities:</label><%= f.text_field :authorities, :class => 'text-long' %></p>
      <p><label>Body:</label><%= f.text_area :body %></p>
      <p><label>Extra:</label><%= f.text_area :extra %></p>
    </fieldset>

    <h3>Alternate Languages for Title</h3>
    <fieldset class="languages">
    <% f.fields_for :languages do |language| %>
      <div class="language">
        <p><label>Language:</label><%= language.text_field :language, :class => 'text-long' %></p>
      </div>
      <div class="words">
        <p><label>Words:</label><%= language.text_field :words, :class => 'text-long' %>
        </p>
      </div>
    <% end %>
    </fieldset>
    <input type="submit" value="Proceed to Attach Books" />
<% end %>
<% content_for :head do %>
  <%= include_puny_mce :plugins => %w(Paste Image Link TextColor EditSource Entities) %>
<% end %>
<%= puny_mce [%w(body category_body), %w(extra category_extra)], :profile => :almost %>

app/views/admin/categories/_list.html.erb
<% if controller.action_name != 'list' %>
  <h3>Recently Added or Updated Categories <a href="/admin/categories/list">(View All)</a></h3>
<% else %>
  <h3>All Categories</h3>
<% end %>
<table cellpadding="0" cellspacing="0" class="list">
<% @categories.each do |category| %>
  <tr>
    <td><%= category.title %></td>
    <td class="action"><a href="<%= category_path(category) %>" class="view">View</a><a href="<%= edit_admin_category_path(category) %>" class="edit">Edit</a><a href="/admin/categories/destroy/<%= category.id %>" class="delete">Delete</a></td>
  </tr>                        
<% end %>
</table>

app/views/admin/categories/add_books.html.erb
<% form_for [:admin, @category], :url => {:action => 'attach', :id => @category.id} do |f| %>
  <h3>Input a Book</h3>
  <fieldset>
    <p>
      <label>Book Title (Short or Long):</label>
      <input class="text-long ac_sources" />
      <% @category.books.each do |book| %>
        <input type="hidden" name="category[book_ids][]" id="book_<%= book.id %>" value="<%= book.id %>" />
      <% end %>
    </p>
  </fieldset>

  <h3>Bibliography</h3>
  <div class="ui-state-highlight bibliography" <%= 'style="display: none"' unless @category.has_bibliography? %>>
    <% f.fields_for :books do |book| %>
      <% unless book.object.modern? %>
        <div>
          <span class="ui-icon ui-icon-radio-on bullet"></span>
          <span><%= book.object.short_title %></span>
          <a href="javascript:void(0)" id="book_link_<%= book.object.id %>" class="close"><span class="ui-icon ui-icon-close"></span></a>
        </div>
      <% end %>
    <% end %>
  </div>

  <h3>Modern Sources</h3>
  <div class="ui-state-highlight modern_sources" <%= 'style="display: none"' unless @category.has_modern? %>>
    <% f.fields_for :books do |book| %>
      <% if book.object.modern? %>
        <div>
          <span class="ui-icon ui-icon-radio-on bullet"></span>
          <span><%= book.object.short_title %></span>
          <a href="javascript:void(0)" id="book_link_<%= book.object.id %>" class="close"><span class="ui-icon ui-icon-close"></span></a>
        </div>
      <% end %>
    <% end %>
  </div>

  <input type="submit" value="Save Attached Books" />
<% end %>

app/views/admin/categories/debug.html.erb
<form action="" class="jNice">
<h3>Sample section</h3>
<table cellpadding="0" cellspacing="0">
  <tr>
    <td>Vivamus rutrum nibh in felis tristique vulputate</td>
    <td class="action"><a href="#" class="view">View</a><a href="#" class="edit">Edit</a><a href="#" class="delete">Delete</a></td>
  </tr>                        

  <tr class="odd">
    <td>Duis adipiscing lorem iaculis nunc</td>
    <td class="action"><a href="#" class="view">View</a><a href="#" class="edit">Edit</a><a href="#" class="delete">Delete</a></td>
  </tr>                        
  <tr>
    <td>Donec sit amet nisi ac magna varius tempus</td>
    <td class="action"><a href="#" class="view">View</a><a href="#" class="edit">Edit</a><a href="#" class="delete">Delete</a></td>
  </tr>                        
  <tr class="odd">
    <td>Duis ultricies laoreet felis</td>
    <td class="action"><a href="#" class="view">View</a><a href="#" class="edit">Edit</a><a href="#" class="delete">Delete</a></td>
  </tr>                        
  <tr>
    <td>Vivamus rutrum nibh in felis tristique vulputate</td>
    <td class="action"><a href="#" class="view">View</a><a href="#" class="edit">Edit</a><a href="#" class="delete">Delete</a></td>
  </tr>                        
</table>

<h3>Another section</h3>
<fieldset>
  <p><label>Sample label:</label><input type="text" class="text-long" /></p>
  <p><label>Sample label:</label><input type="text" class="text-medium" /><input type="text" class="text-small" /><input type="text" class="text-small" /></p>
  <p><label>Sample label:</label>
  <select>
    <option>Select one</option>
    <option>Select two</option>
    <option>Select tree</option>
    <option>Select one</option>
    <option>Select two</option>
    <option>Select tree</option>
  </select>
  </p>
  <p><label>Sample label:</label><textarea rows="1" cols="1"></textarea></p>
  <input type="submit" value="Submit Query" />
</fieldset>
</form>

app/views/admin/categories/edit.html.erb
<% submit_label = 'Save Category' %>
<%= render :partial => 'form', :locals => {:submit_label => submit_label} %>

app/views/admin/categories/index.html.erb
<%= render :partial => 'list' %>
<% form_for [:admin, @category] do |f| %>
  <h3>Quick Category Add</h3>
  <fieldset>
    <p><label>Title:</label><input type="text" name="category[title]" class="text-long" /></p>
    <p><label>Redirect To:</label>
      <input type="text" class="text-long autocomplete" />
      <input type="hidden" name="category[redirect_id]" >
    </p>
    <div class="ui-state-highlight redirect">
      <span class="ui-icon ui-icon-radio-on bullet"></span>
      <span id="redirect"></span>
      <a href="javascript:void(0)" class="close"><span class="ui-icon ui-icon-close"></span></a>
    </div>
    <p><label>Authorities (Comma Separated List):</label><input type="text" name="category[authorities]" class="text-long" /></p>
    <p><label>Category Text:</label><textarea name="category[body]" id="book_body"></textarea></p>
    <input type="submit" value="Create New Category" />
  </fieldset>
<% end %>
<% content_for :head do %>
  <%= include_puny_mce :plugins => %w(Paste Image Link TextColor EditSource Entities) %>
<% end %>
<%= puny_mce [%w(body book_body)], :profile => :almost %>

app/views/admin/categories/new.html.erb
<% submit_label = 'Create New Category' %>
<%= render :partial => 'form', :locals => {:submit_label => submit_label} %>